# Generated by Django 4.1.8 on 2023-05-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_remove_comment_image_alter_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
