# Generated by Django 4.1.8 on 2023-05-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0004_remove_minifoodallergy_allergy_pic_and_more"),
        ("posts", "0004_comment_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="allergy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posts",
                to="database.allergy",
            ),
        ),
    ]
