# Generated by Django 4.1.8 on 2023-05-01 12:22

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default=users.models.default_profile_pic,
                null=True,
                upload_to="profile_pics",
            ),
        ),
    ]
