# Generated by Django 4.1.8 on 2023-04-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arabicName", models.CharField(max_length=500)),
                ("englishName", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arabicName", models.CharField(max_length=500)),
                ("englishName", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="FoodAllergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergy_pic",
                    models.ImageField(blank=True, null=True, upload_to="Allergy_pics"),
                ),
                ("arabicDescription", models.CharField(max_length=500)),
                ("englishDescription", models.CharField(max_length=500)),
                ("arabicName", models.CharField(max_length=500)),
                ("englishName", models.CharField(max_length=500)),
                ("arabicSymptoms", models.CharField(max_length=500)),
                ("englishSymptoms", models.CharField(max_length=500)),
                ("arabicProtection", models.CharField(max_length=500)),
                ("englishProtection", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arabicName", models.CharField(max_length=500)),
                ("englishName", models.CharField(max_length=500)),
                ("allergy", models.ManyToManyField(to="database.allergy")),
                ("food", models.ManyToManyField(to="database.food")),
            ],
        ),
    ]
