# Generated by Django 4.1.8 on 2023-05-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "database",
            "0002_alter_allergy_arabicname_alter_allergy_englishname_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MiniFoodAllergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergy_pic",
                    models.ImageField(blank=True, null=True, upload_to="Allergy_pics"),
                ),
                (
                    "arabicName",
                    models.CharField(max_length=500, verbose_name="Arabic name"),
                ),
                (
                    "englishName",
                    models.CharField(max_length=500, verbose_name="English name"),
                ),
            ],
        ),
    ]
