# Generated by Django 4.1.8 on 2023-05-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0003_minifoodallergy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="minifoodallergy",
            name="allergy_pic",
        ),
        migrations.AddField(
            model_name="minifoodallergy",
            name="mini_allergy_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="miniAllergy_pics"
            ),
        ),
    ]
