# Generated by Django 4.1.8 on 2023-05-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "database",
            "0002_alter_allergy_arabicname_alter_allergy_englishname_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("result", models.CharField(max_length=500)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.category",
                    ),
                ),
            ],
        ),
    ]
