# Generated by Django 4.1.8 on 2023-05-08 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("model_ai", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageClassification",
        ),
    ]
