# Generated by Django 4.1.8 on 2023-05-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_order_product_image_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
