# Generated by Django 4.1.8 on 2023-05-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_alter_rating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
            ),
        ),
    ]
